//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntrotoEntityFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployeePosition
    {
        public string Level_Name { get; set; }
        public string PostionName { get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> AddressId { get; set; }
        public decimal Salary { get; set; }
    }
}
